"""Materialize a private Coral runtime workspace for DELIRIUM.AI."""

from __future__ import annotations

import argparse
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path


THIS_DIR = Path(__file__).resolve().parent
REPO_ROOT = THIS_DIR.parents[1]
OUTPUT_ROOT = Path.home() / ".local" / "share" / "delirium-coral"
RUNTIME_DIR_NAME = "delirium-coral"
ORCHESTRATION_PREFIX = Path("orchestration") / "coral"
EXCLUDED_NAMES = {
    ".git",
    ".hg",
    ".svn",
    ".tmp",
    ".venv",
    "venv",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".runtime",
    "data",
    ".env",
}
EXCLUDED_SUFFIXES = {".pyc", ".pyo"}


def _should_skip(relative_path: Path) -> bool:
    if any(part in EXCLUDED_NAMES for part in relative_path.parts):
        return True
    if relative_path.parts[:2] == ORCHESTRATION_PREFIX.parts:
        return True
    return relative_path.suffix in EXCLUDED_SUFFIXES


def _copy_product_tree(repo_root: Path, destination: Path) -> None:
    def ignore(directory: str, names: list[str]) -> list[str]:
        base = Path(directory)
        relative_dir = base.relative_to(repo_root)
        ignored: list[str] = []
        for name in names:
            candidate = relative_dir / name if relative_dir != Path(".") else Path(name)
            if _should_skip(candidate):
                ignored.append(name)
        return ignored

    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(repo_root, destination, ignore=ignore)


def _load_sources_config() -> dict:
    config_path = THIS_DIR / "judge_sources.json"
    return json.loads(config_path.read_text(encoding="utf-8"))


def _render_task_yaml() -> str:
    return """task:
  name: "DELIRIUM.AI Productization"
  description: |
    Productize DELIRIUM.AI toward a local-first Delirium Core milestone.
    The behavioral source of truth is 01_CAHIER_DES_CHARGES/CDC_COMPORTEMENTAL.md.
    README.md is stale where it still says there is no code and no prototype.
  tips: |
    - Prioritize Delirium Core over OmniArxiv.
    - Respect CDC_COMPORTEMENTAL.md before any other behavior document.
    - Do not invent undocumented product decisions.
    - Favor working software, tests, and docs over speculative rewrites.

grader:
  timeout: 900
  direction: maximize
  args:
    milestone: "Delirium Core"
    judge_model: "gpt-5.4"
    judge_reasoning_effort: "xhigh"
    judge_timeout: 300
    pytest_targets:
      - "tests/test_behavior.py"
      - "tests/test_adversarial.py"

agents:
  count: 3
  runtime: codex
  model: gpt-5.4
  runtime_options:
    model_reasoning_effort: xhigh

workspace:
  results_dir: "./results"
  repo_path: "./product"
  setup:
    - "python3 -m pip install --upgrade pip"
    - "python3 -m pip install -r requirements.txt"

run:
  verbose: false
  ui: false
  session: tmux
"""


def _write_runtime_readme(runtime_dir: Path) -> None:
    text = """# DELIRIUM.AI Coral Runtime

This directory is generated by `orchestration/coral/materialize_task.py`.

- `product/` is the visible codebase under evaluation.
- `eval/` contains the hidden grader assets copied into Coral private storage.
- `task.yaml` pins Codex to `gpt-5.4` with `xhigh` reasoning effort.
"""
    (runtime_dir / "README.md").write_text(text, encoding="utf-8")


def build_runtime_tree(
    output_dir: Path | None = None,
    repo_root: Path | None = None,
) -> Path:
    repo_root = (repo_root or REPO_ROOT).resolve()
    output_dir = (output_dir or OUTPUT_ROOT).resolve()
    runtime_dir = output_dir / RUNTIME_DIR_NAME
    product_dir = runtime_dir / "product"
    eval_dir = runtime_dir / "eval"
    results_dir = runtime_dir / "results"

    runtime_dir.mkdir(parents=True, exist_ok=True)
    results_dir.mkdir(parents=True, exist_ok=True)
    _copy_product_tree(repo_root, product_dir)

    if eval_dir.exists():
        shutil.rmtree(eval_dir)
    shutil.copytree(THIS_DIR / "eval", eval_dir)

    (runtime_dir / "task.yaml").write_text(_render_task_yaml(), encoding="utf-8")
    shutil.copy2(THIS_DIR / "judge_sources.json", runtime_dir / "judge_sources.json")
    shutil.copy2(THIS_DIR / "judge_rubric.md", runtime_dir / "judge_rubric.md")

    metadata = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "repo_root": str(repo_root),
        "runtime_dir": str(runtime_dir),
        "canonical_sources": _load_sources_config()["canonical_sources"],
    }
    (runtime_dir / "materialization.json").write_text(
        json.dumps(metadata, indent=2),
        encoding="utf-8",
    )
    _write_runtime_readme(runtime_dir)
    return runtime_dir


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Materialize a private Coral task workspace for DELIRIUM.AI.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=OUTPUT_ROOT,
        help="Base directory where the runtime workspace will be written.",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=REPO_ROOT,
        help="Repository root to snapshot into the visible product directory.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    runtime_dir = build_runtime_tree(output_dir=args.output_dir, repo_root=args.repo_root)
    print(runtime_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
